
/* ============================================================
   PromptAlpha — Sample Prompt Library
   Curated set of institutional-grade prompt templates (10 total,
   added incrementally). Edit this file to add, remove, or rewrite
   entries — nothing in index.html needs to change when you do.

   Each category's "key" must match a key in the MODES object in
   index.html (e.g. "equity", "credit") so mode selection can
   pre-filter the library to the matching category.

   Fields per item:
   - title, description, difficulty ("Beginner"|"Intermediate"|"Advanced")
   - text: the actual prompt content
   ============================================================ */

const LIBRARY = [
  { key: "equity", emoji: "📈", name: "Equity Research", items: [
    { title: "Institutional initiation report", description: "Comprehensive buy-side initiation coverage with full standard structure.", difficulty: "Advanced", text: "You are a senior buy-side equity research analyst initiating coverage on a publicly listed company for a long-term institutional investor.\n\nPrepare a comprehensive initiation report that evaluates the company's quality, competitive position and long-term investment potential.\n\nAssess the company's business model, products and services, industry dynamics, market share, competitive advantages, management quality and capital allocation strategy.\n\nAnalyze historical revenue growth, profitability, operating margins, free cash flow generation, return on invested capital and balance sheet strength.\n\nEvaluate each major business segment individually, discussing growth opportunities, profitability and strategic importance.\n\nReview the competitive landscape and identify the company's sustainable competitive advantages as well as emerging threats.\n\nIdentify the major drivers expected to influence earnings over the next three to five years.\n\nHighlight key investment risks including macroeconomic exposure, regulatory changes, technological disruption, customer concentration, execution risk and competitive pressures.\n\nPrepare the report using the following structure:\n\n1. Investment Thesis\n2. Business Overview\n3. Industry Analysis\n4. Business Segment Review\n5. Financial Performance\n6. Competitive Position\n7. Growth Opportunities\n8. Investment Risks\n9. Valuation Considerations\n10. Investment Recommendation\n11. Areas for Further Research\n\nEnsure every conclusion is evidence-based, clearly separating factual observations from analytical judgement. Focus on insights that could influence long-term investment decisions rather than descriptive summaries." },
  ]},
  { key: "earnings", emoji: "📞", name: "Earnings Calls", items: [
    { title: "Institutional post-earnings briefing", description: "Structured post-earnings note evaluating tone, guidance, and investor concerns.", difficulty: "Advanced", text: "You are a senior equity research analyst preparing a post-earnings briefing for institutional investors.\n\nAnalyze the company's latest earnings call transcript and identify the information most relevant to an investment decision.\n\nDo not summarize the transcript. Instead, evaluate management's tone, confidence, strategic priorities, execution capability and future outlook.\n\nAssess commentary relating to revenue growth, margins, operating expenses, pricing, customer demand, capital expenditure, geographic performance, competitive positioning and future guidance.\n\nReview analyst questions carefully and identify recurring investor concerns, management's willingness to answer difficult questions and areas where management avoided providing clarity.\n\nDetermine whether management appears more optimistic or cautious compared with previous quarters.\n\nIdentify new disclosures, strategic shifts, guidance revisions or operational changes that may materially affect future earnings expectations.\n\nPrepare the report using the following format:\n\n1. Executive Summary\n2. Business Updates\n3. Financial Highlights\n4. Management Tone Assessment\n5. Guidance Analysis\n6. Analyst Questions & Responses\n7. Positive Signals\n8. Areas of Concern\n9. Investment Implications\n10. Key Follow-up Questions\n\nSupport all conclusions using evidence from the transcript and clearly distinguish facts from interpretation." },
  ]},
  { key: "sec", emoji: "📑", name: "SEC Filing Analysis", items: [
    { title: "Institutional annual report review", description: "Full-structure buy-side note on a company's latest annual report.", difficulty: "Advanced", text: "You are a senior buy-side equity research analyst at a global asset management firm.\n\nYour objective is to analyze a company's latest annual report and prepare an institutional-quality investment research note. Do not simply summarize the filing. Instead, identify the information that could materially influence an investment decision.\n\nReview the company's business model, industry position, revenue drivers, profitability, margins, operating leverage, cash flow generation, balance sheet strength, capital allocation strategy, research & development spending, acquisitions, debt profile and competitive advantages.\n\nIdentify significant changes compared with the previous year's annual report, including strategic initiatives, new risks, accounting policy changes, management commentary and capital allocation priorities.\n\nEvaluate the sustainability of revenue growth, earnings quality, free cash flow generation and return on invested capital.\n\nAssess whether management's long-term strategy is credible and supported by financial performance.\n\nHighlight major investment catalysts over the next 12-24 months as well as the key risks that could materially impact valuation.\n\nSupport every important conclusion with evidence from the annual report.\n\nPrepare the report using the following structure:\n\n1. Executive Summary\n2. Business Overview\n3. Financial Performance\n4. Business Segment Analysis\n5. Capital Allocation\n6. Competitive Position\n7. Key Risks\n8. Growth Catalysts\n9. Valuation Considerations\n10. Investment Conclusion\n11. Questions for Further Research\n\nMaintain a professional tone suitable for institutional investors. Clearly distinguish factual observations from analytical opinions." },
    { title: "Comprehensive SEC filing review", description: "Full disclosure review across MD&A, risk factors, notes, and governance.", difficulty: "Advanced", text: "You are a senior buy-side equity research analyst performing a comprehensive review of a company's latest SEC filing.\n\nYour objective is to identify disclosures that could materially influence an investment decision rather than summarizing the document.\n\nReview the Business Overview, Risk Factors, Management Discussion & Analysis (MD&A), Financial Statements, Notes to the Accounts, Legal Proceedings and Corporate Governance sections.\n\nIdentify significant changes from previous filings, including new risk disclosures, acquisitions, divestitures, accounting policy changes, capital allocation decisions and management commentary.\n\nAssess financial performance, balance sheet quality, liquidity, cash flow generation, earnings quality and capital allocation.\n\nReview notes relating to debt, leases, litigation, contingent liabilities, pensions, stock-based compensation and tax matters.\n\nHighlight accounting disclosures, legal risks or operational developments that may materially impact future earnings or valuation.\n\nPrepare the report using the following structure:\n\n1. Executive Summary\n2. Business Overview\n3. Financial Performance\n4. Balance Sheet & Liquidity\n5. Cash Flow Analysis\n6. Risk Factors\n7. Accounting & Disclosure Review\n8. Significant Changes from Prior Filings\n9. Investment Implications\n10. Follow-up Questions\n\nClearly distinguish factual disclosures from analytical interpretation and support every conclusion with evidence from the filing." },
  ]},
  { key: "credit", emoji: "🏦", name: "Credit Research", items: [
    { title: "Institutional credit risk assessment", description: "Full credit opinion covering liquidity, leverage, and default risk.", difficulty: "Advanced", text: "You are a senior credit analyst at a global investment firm evaluating the creditworthiness of a company.\n\nYour objective is to determine the company's ability to meet its financial obligations and identify potential risks to lenders and investors.\n\nAnalyze the company's liquidity, leverage, debt maturity profile, interest coverage, cash flow generation, working capital, covenant compliance and refinancing requirements.\n\nEvaluate historical trends in debt levels, operating cash flow and capital allocation decisions.\n\nAssess the sustainability of cash generation under different business conditions and identify scenarios that could lead to financial stress.\n\nReview contingent liabilities, off-balance-sheet obligations, litigation, guarantees and other factors that may affect credit quality.\n\nIdentify strengths supporting the company's credit profile as well as weaknesses that could increase default risk.\n\nPrepare the report using the following structure:\n\n1. Executive Summary\n2. Liquidity Assessment\n3. Leverage Analysis\n4. Cash Flow Review\n5. Debt Structure & Maturity Profile\n6. Covenant & Refinancing Risk\n7. Credit Strengths\n8. Credit Risks\n9. Stress Scenario Analysis\n10. Overall Credit Opinion\n\nBase every conclusion on available financial information and clearly explain the reasoning behind each assessment." },
  ]},
  { key: "modeling", emoji: "📊", name: "Financial Modeling", items: [
    { title: "Financial statement analysis", description: "Full assessment of financial health from the three core statements.", difficulty: "Advanced", text: "You are a senior financial analyst responsible for evaluating a company's financial health using its Income Statement, Balance Sheet and Cash Flow Statement.\n\nYour objective is to identify the company's financial strengths, weaknesses, risks and long-term sustainability rather than simply describing the numbers.\n\nAnalyze revenue growth, profitability, gross margins, operating margins, EBITDA, net income, earnings quality, free cash flow, return on equity, return on invested capital and capital efficiency.\n\nEvaluate liquidity, leverage, debt servicing ability, working capital management and balance sheet quality.\n\nIdentify unusual accounting treatments, one-time gains or losses, aggressive accounting practices, changes in accounting policies and potential red flags that could impact earnings quality.\n\nAssess historical trends and determine whether financial performance is improving, deteriorating or remaining stable.\n\nBenchmark financial performance against industry norms where appropriate.\n\nPrepare the report using the following structure:\n\n1. Executive Summary\n2. Income Statement Analysis\n3. Balance Sheet Analysis\n4. Cash Flow Analysis\n5. Profitability Assessment\n6. Liquidity & Solvency\n7. Earnings Quality\n8. Financial Risks\n9. Key Takeaways\n10. Overall Financial Health Assessment\n\nSupport every conclusion using evidence from the financial statements and clearly distinguish factual observations from analytical judgement." },
    { title: "DCF valuation review", description: "Peer review of a DCF's assumptions, methodology, and sensitivity before committee.", difficulty: "Advanced", text: "You are a senior equity research analyst reviewing a Discounted Cash Flow (DCF) valuation prepared by another analyst before it is presented to an investment committee.\n\nYour objective is to determine whether the valuation assumptions, methodology and conclusions are reasonable, internally consistent and supported by available evidence.\n\nReview revenue forecasts, operating margin assumptions, tax rates, capital expenditure, depreciation, working capital assumptions, free cash flow projections and terminal value calculations.\n\nEvaluate the weighted average cost of capital (WACC), cost of equity, cost of debt, beta assumptions, capital structure and terminal growth rate.\n\nIdentify unrealistic assumptions, inconsistencies with historical performance, management guidance or industry expectations.\n\nAssess the sensitivity of intrinsic value to changes in revenue growth, operating margins, WACC and terminal growth assumptions.\n\nExplain which assumptions have the greatest impact on valuation and identify key risks that could materially affect fair value.\n\nPrepare the report using the following structure:\n\n1. Executive Summary\n2. Valuation Methodology Review\n3. Forecast Assumptions\n4. WACC Assessment\n5. Terminal Value Review\n6. Sensitivity Analysis\n7. Key Valuation Drivers\n8. Risks & Limitations\n9. Recommended Improvements\n10. Overall Valuation Opinion\n\nSupport every conclusion with evidence and clearly distinguish factual observations from professional judgement." },
    { title: "Three-statement model audit", description: "Audit an existing model for integrity, linkage, and assumption issues before delivery.", difficulty: "Advanced", text: "You are a senior financial modeling specialist responsible for auditing a three-statement financial model before it is delivered to institutional investors.\n\nYour objective is to ensure the model is technically accurate, internally consistent and financially sound. Do not rebuild the model. Instead, identify errors, inconsistencies, unrealistic assumptions and areas for improvement.\n\nReview the Income Statement, Balance Sheet and Cash Flow Statement to ensure they are fully linked and balanced.\n\nCheck formulas, hardcoded values, circular references, balance sheet balancing, retained earnings, debt schedules, working capital calculations, depreciation, capital expenditure, taxes and cash flow reconciliation.\n\nEvaluate forecast assumptions for revenue, margins, operating expenses, working capital, capital expenditure and financing activities.\n\nIdentify broken links, inconsistent calculations, hidden errors and unrealistic assumptions that could materially impact valuation.\n\nPrepare the report using the following structure:\n\n1. Executive Summary\n2. Model Integrity Review\n3. Income Statement Review\n4. Balance Sheet Review\n5. Cash Flow Review\n6. Forecast Assumptions\n7. Formula & Linkage Issues\n8. Key Risks\n9. Recommended Improvements\n10. Overall Model Quality Assessment\n\nSupport every finding with clear evidence and explain why each issue matters from an investment perspective." },
  ]},
  { key: "diligence", emoji: "🔍", name: "Due Diligence", items: [
    { title: "M&A commercial and financial due diligence", description: "VP-level diligence review covering business, financial, and legal risk for a potential acquisition.", difficulty: "Advanced", text: "You are a Vice President in the Mergers & Acquisitions team of a global investment bank conducting commercial and financial due diligence for a potential acquisition.\n\nYour objective is to identify the critical findings that could influence valuation, deal structure, financing or the decision to proceed with the transaction.\n\nReview the company's financial statements, annual reports, investor presentations, earnings transcripts and available industry information.\n\nEvaluate business quality, revenue diversification, customer concentration, supplier dependence, competitive positioning, operational efficiency, profitability, cash flow generation and long-term growth prospects.\n\nIdentify aggressive accounting policies, contingent liabilities, litigation exposure, tax risks, off-balance-sheet obligations and operational risks.\n\nAssess management quality, governance standards, capital allocation discipline and execution capability.\n\nPrepare the report using the following structure:\n\n1. Executive Summary\n2. Business Assessment\n3. Commercial Review\n4. Operational Review\n5. Financial Performance\n6. Financial Risks\n7. Legal & Regulatory Risks\n8. Management Assessment\n9. Valuation Considerations\n10. Key Due Diligence Findings\n11. Recommended Next Steps\n\nPrioritize actionable findings over descriptive summaries and clearly identify areas requiring additional investigation." },
  ]},
  { key: "portfolio", emoji: "📋", name: "Portfolio Management", items: [
    { title: "Investment thesis and portfolio recommendation", description: "Full PM-level synthesis into a committee-ready buy/hold/sell recommendation.", difficulty: "Advanced", text: "You are a senior portfolio manager at a global asset management firm responsible for making long-term investment decisions.\n\nYou have access to annual reports, quarterly reports, earnings transcripts, financial statements, valuation models and industry research.\n\nYour objective is to determine whether the company deserves a place in a long-term investment portfolio.\n\nDo not summarize the available information. Instead, synthesize it into a clear, evidence-based investment recommendation suitable for an institutional investment committee.\n\nEvaluate business quality by assessing competitive advantages, market position, pricing power, innovation, customer retention, management execution and long-term strategy.\n\nAssess financial performance through revenue growth, profitability, free cash flow generation, return on invested capital, balance sheet strength, capital allocation and earnings quality.\n\nReview valuation using DCF, comparable company analysis and historical valuation multiples.\n\nDetermine whether the current valuation appropriately reflects future growth opportunities and business risks.\n\nIdentify the most important investment catalysts over the next 12-24 months, including product launches, acquisitions, geographic expansion, operational improvements and regulatory developments.\n\nEvaluate downside risks including competition, technological disruption, macroeconomic conditions, litigation, regulation and execution risk.\n\nPrepare the report using the following structure:\n\n1. Executive Investment Summary\n2. Business Quality Assessment\n3. Financial Performance Review\n4. Competitive Position\n5. Valuation Assessment\n6. Growth Catalysts\n7. Key Investment Risks\n8. Bull, Base and Bear Case Analysis\n9. Investment Recommendation (Strong Buy, Buy, Hold, Reduce or Sell)\n10. Portfolio Considerations\n11. Key Metrics to Monitor\n\nSupport every recommendation with evidence. Clearly distinguish factual observations from analytical judgement and explicitly state assumptions where required." },
  ]},
];
